madre(ann,henry).
madre(ann,mary).
madre(jane,mark).
madre(jane,francis).
madre(annette,jonathan).
madre(mary,bill).
madre(janice,louise).
madre(lucy,janet).
madre(louise,caroline).
madre(caroline,david).
madre(caroline,janet).
padre(henry,jonathan).
padre(john,mary).
padre(francis,william).
padre(francis,louise).
padre(john,mark).
padre(gavin,lucy).
padre(john,francis).
padres(victoria,george).
padres(victoria,edward).
padres(X,Y):-madre(X,Y).
padres(X,Y):-padre(X,Y).
padres(elizabeth,charles).
padres(elizabeth,andrew).
antepasado(X,Y):-padres(X,Y).
antepasado(X,Y):-padres(X,Z),antepasado(Z,Y).

/*Reglas*/

hijo_de(A,B):-padres(B,A).
abuelo_de(A,B):-padre(A,C),padres(C,B).
abuela_de(A,B):-madre(A,C),padres(C,B).
bisabuelo_de(A,B):-padre(A,C),abuelo_de(C,B).
bisabuelo_de(A,B):-padre(A,C),abuela_de(C,B).